[package]
name = "dunnos"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"
opt-level = 1

[profile.release]
panic = "abort"

[lints.clippy]
all = "deny"          # Deny all lints by default
pedantic = "warn"     # Warn for pedantic lints
nursery = "allow"     # Allow nursery lints (new and experimental)
